name: 'Install Packages (brew)'
description: 'Install required packages using brew'

inputs:
  need-boost-system:
    # NB: Brew only has one boost package, which we need to have anyway, so this input is ignored.
    # However, we keep it around for consistency with the other package installation actions.
    description: 'whether version under test needs boost thread library'
    required: false
    default: false
  need-boost-thread:
    # NB: Brew only has one boost package, which we need to have anyway, so this input is ignored.
    # However, we keep it around for consistency with the other package installation actions.
    description: 'whether version under test needs boost thread library'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # Make sure our package list is up to date
        brew update
        # Make sure we have all the libraries we want
        brew install boost
        brew install zlib
        brew install libpng
        brew install libjpeg
        brew install libtiff
        brew install openexr
        brew install sdl
        # Make sure we have all the tools we want
        brew install automake
        brew install pkg-config
